services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant-data:/qdrant/storage
    container_name: qdrant
    restart: unless-stopped
networks:
  qdrant-network:
    driver: bridge